In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [5]:
df.shape

(5572, 3)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
## Train- Test Split

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [9]:
X_train.shape

(4457,)

In [10]:
X_test.shape

(1115,)

In [11]:
type(X_train)

pandas.core.series.Series

In [12]:
X_train[:4]

2216        Prabha..i'm soryda..realy..frm heart i'm sory
4261        Are you plans with your family set in stone ?
3930                              Yes. Nigh you cant aha.
4588    I'll see if I can swing by in a bit, got some ...
Name: Message, dtype: object

In [13]:
type(y_train)

pandas.core.series.Series

In [14]:
type(X_train.values)

numpy.ndarray

In [15]:
## Create bag of words representation using CountVectorizer

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7774 sparse matrix of type '<class 'numpy.int64'>'
	with 59540 stored elements in Compressed Sparse Row format>

In [17]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
X_train_cv.shape

(4457, 7774)

In [19]:
v.get_feature_names_out()[1771]

'cheetos'

In [20]:
v.vocabulary_

{'prabha': 5363,
 'soryda': 6350,
 'realy': 5623,
 'frm': 3032,
 'heart': 3399,
 'sory': 6349,
 'are': 1041,
 'you': 7734,
 'plans': 5245,
 'with': 7580,
 'your': 7740,
 'family': 2786,
 'set': 6057,
 'in': 3651,
 'stone': 6511,
 'yes': 7719,
 'nigh': 4793,
 'cant': 1636,
 'aha': 864,
 'll': 4172,
 'see': 6009,
 'if': 3612,
 'can': 1625,
 'swing': 6682,
 'by': 1584,
 'bit': 1361,
 'got': 3223,
 'some': 6310,
 'things': 6871,
 'to': 6957,
 'take': 6714,
 'care': 1650,
 'of': 4907,
 'here': 3431,
 'firsg': 2893,
 'thnx': 6887,
 'dude': 2493,
 'guys': 3302,
 'out': 5027,
 '2nite': 405,
 'its': 3779,
 'like': 4120,
 'that': 6836,
 'hotel': 3524,
 'dusk': 2508,
 'game': 3088,
 'think': 6872,
 'solve': 6308,
 'puzzles': 5522,
 'area': 1042,
 'thing': 6870,
 'this': 6881,
 'much': 4655,
 'buzy': 1578,
 'it': 3771,
 'should': 6142,
 'about': 752,
 'lt': 4262,
 'gt': 3282,
 'min': 4504,
 'great': 3258,
 'diddy': 2314,
 'is': 3759,
 'my': 4688,
 'neighbor': 4755,
 'and': 952,
 'comes': 1918,
 'f

In [21]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
np.where(X_train_np[0]!=0)

(array([3032, 3399, 5363, 5623, 6349, 6350]),)

In [25]:
X_train[:4]

2216        Prabha..i'm soryda..realy..frm heart i'm sory
4261        Are you plans with your family set in stone ?
3930                              Yes. Nigh you cant aha.
4588    I'll see if I can swing by in a bit, got some ...
Name: Message, dtype: object

In [28]:
X_train_np[0][1150]

0

In [29]:
## Train the naive bayes model

In [30]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [32]:
X_test_cv = v.transform(X_test)

In [33]:
## evaluate performance

In [34]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       979
           1       0.99      0.90      0.95       136

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [35]:
emails = [
    'Hey Parth, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])